import Department
import Diagnosis
import Doctors
import Patients
import diagnosis_room
import Group
import examine_entry
import payment_type
import bill_register
import sample
import package
import laundry
import blood
import dashboards
import expense
import ward
import discount
import opd
import admission
import money_receipt
import cash_collection
import commission
import appointment
import optics
import wizard
import inventory
import advance_cash
# import accounting_report

