import Department
import Diagnosis
import Doctors
import Patients
import diagnosis_room
import Group
import examine_entry
import bill_register
import sample
import package
import laundry
import blood
import dashboards
import expense
import ward
